#### numpy 모듈의 호출

In [1]:
import numpy as np

In [2]:
# Further example
import pprint

#### array의 생성

In [3]:
a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]

In [4]:
a = np.array(a, int)
a

array([1, 2, 3, 4, 5])

In [5]:
test_array = np.array(["1", "4", 5.0, 8], float)
test_array

array([1., 4., 5., 8.])

In [6]:
type(test_array)

numpy.ndarray

In [7]:
type(test_array[3])

numpy.float64

In [8]:
test_array = np.array([1, 4, 5, "8"], float)  # String Type의 데이터를 입력해도
test_array

array([1., 4., 5., 8.])

In [9]:
type(test_array[3])  # Float Type으로 자동 형변환을 실시

numpy.float64

In [10]:
a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]
a[0] is b[-1]

True

In [11]:
a = np.array(a)
b = np.array(b)
a[0] is b[-1]

False

In [12]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
a[1] is b[-2]

False

In [13]:
a.dtype

dtype('int64')

In [14]:
test_array.dtype  # Array(배열) 전체의 데이터 Type을 반환함

dtype('float64')

In [15]:
a = [[1, 2, 3], [4, 5, 6], [4, 5, 6]]

In [16]:
np.array(a).shape

(3, 3)

In [17]:
# Further example
ymnseol_a = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]], float)
print("Shape:", {ymnseol_a.shape})
print("Rank:", {np.linalg.matrix_rank(ymnseol_a)})
pprint.pprint(np.linalg.eig(ymnseol_a)[0])

Shape: {(3, 3)}
Rank: {3}
array([1., 1., 1.])


In [18]:
# Further example
ymnseol_a = np.array([[1, 0, 0], [1, 0, 0], [0, 0, 1]], float)
print("Shape:", {ymnseol_a.shape})
print("Rank:", {np.linalg.matrix_rank(ymnseol_a)})
pprint.pprint(np.linalg.eig(ymnseol_a)[0])

Shape: {(3, 3)}
Rank: {2}
array([0., 1., 1.])


In [19]:
# Further example
ymnseol_a = np.array([[1, 0, 0], [2, 0, 0], [3, 0, 0]], float)
print("Shape:", {ymnseol_a.shape})
print("Rank:", {np.linalg.matrix_rank(ymnseol_a)})
pprint.pprint(np.linalg.eig(ymnseol_a)[0])

Shape: {(3, 3)}
Rank: {1}
array([0., 0., 1.])


#### array shape

In [20]:
vector = [1, 2, 3, 4]
np.array(vector, int).shape

(4,)

In [21]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int)

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [22]:
tensor = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
]
np.array(tensor, int).shape

(4, 3, 4)

In [23]:
np.array(tensor, int).ndim

3

In [24]:
np.array(tensor, int).size

48

#### numpy dtype

In [25]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], dtype=np.int8)

In [26]:
a.dtype

dtype('int8')

In [27]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32).nbytes

24

In [28]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32).nbytes

24

In [29]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.int8).nbytes

6

In [30]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float64).nbytes

48