In [1]:
import numpy as np

#### reshape

In [2]:
test_matrix = [[1, 2, 3, 4], [1, 2, 5, 8]]
np.array(test_matrix).shape

(2, 4)

In [3]:
np.array(test_matrix).reshape(4, 2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [4]:
np.array(test_matrix).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [5]:
np.array(test_matrix).reshape(
    8,
)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [6]:
np.array(test_matrix).reshape(2, 4).shape

(2, 4)

In [7]:
np.array(test_matrix).reshape(2, -1)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [8]:
np.array(test_matrix).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [9]:
np.array(test_matrix).reshape(1, -1, 2)

array([[[1, 2],
        [3, 4],
        [1, 2],
        [5, 8]]])

In [14]:
np.array(test_matrix).reshape(1, -1, 2).shape

(1, 4, 2)

In [13]:
np.array(test_matrix).reshape(1, -1, 2).ndim

3

In [10]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [11]:
# Further example
np.array(test_matrix).reshape(-1, 3)

ValueError: cannot reshape array of size 8 into shape (3)

In [12]:
# Further example
np.array(test_matrix).reshape(16,)

ValueError: cannot reshape array of size 8 into shape (16,)

#### flat or flatten()

In [15]:
test_matrix = [[[1, 2, 3, 4], [1, 2, 5, 8]], [[1, 2, 3, 4], [1, 2, 5, 8]]]
np.array(test_matrix)

array([[[1, 2, 3, 4],
        [1, 2, 5, 8]],

       [[1, 2, 3, 4],
        [1, 2, 5, 8]]])

In [16]:
np.array(test_matrix).flatten().size

16

In [17]:
np.array(test_matrix).flatten().shape

(16,)