In [1]:
import numpy as np

#### arange

In [2]:
list(range(0, 10, 3))

[0, 3, 6, 9]

In [3]:
type(list(range(30)))

list

In [4]:
# range: List의 range와 같은 효과,
# integer로 0부터 29까지 배열추출
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.arange(0, 5, 0.5)  # floating point도 표시가능함

In [13]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

#### ones, zeros & empty

In [ ]:
# 10 - zero vector 생성
np.zeros(shape=(10,), dtype=np.int8)

In [22]:
np.zeros((2, 5))  # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [24]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [87]:
np.empty(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [88]:
np.empty((10, 5))

array([[3.31183839e-033, 6.98348270e-077, 2.62395837e+179,
        1.63649909e-310, 2.34147659e-057],
       [1.39804065e-076, 7.57877360e-096, 6.01347002e-154,
        7.11517567e-038, 3.24249365e-086],
       [1.21089429e-099, 2.42015693e-052, 4.90483617e-062,
        1.39804328e-076, 1.14583381e-259],
       [4.56335201e-072, 3.11593324e+179, 1.69082216e-310,
        1.18295070e-076, 4.08596608e-033],
       [8.99060591e-096, 1.39804329e-076, 2.44005307e-154,
        3.44353309e-086, 5.20651931e-090],
       [1.39736850e-076, 1.39642638e-076, 6.12769454e-062,
        1.05162660e-153, 1.39804329e-076],
       [5.98149110e-154, 1.74514512e-310, 2.34147661e-057,
        1.39804065e-076, 7.57877360e-096],
       [4.67296628e-062, 6.98348929e-077, 2.62395837e+179,
        6.01334510e-154, 1.48373151e-076],
       [7.48418596e-067, 1.39804328e-076, 1.05118731e-153,
        8.60961887e-043, 3.24249367e-086],
       [1.80286339e-310, 6.01346953e-154, 1.48710114e-076,
        8.52243828e-096

In [110]:
test_matrix = np.arange(100).reshape(5, -1)
test_matrix.shape

(5, 20)

In [111]:
test_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [118]:
np.zeros_like(test_matrix, dtype=np.float32)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

#### eye, identity & digonal

In [122]:
np.identity(n=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [128]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [ ]:
np.eye(3)

In [129]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [131]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [133]:
np.diag(matrix, k=-1)

array([3, 7])

In [ ]:
np.diag(matrix, k=1)

#### numpy.random

In [140]:
np.random.normal(0, 1, 10).reshape(2, 5)

array([[-0.14950323,  0.57639207,  1.07549923,  0.69918396,  0.4341872 ],
       [ 1.45683959, -0.63192178,  1.75431129,  0.40488555, -1.77115048]])

In [ ]:
np.random.