# Pytorch basics for DL newbies


[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/BoostcampAITech/lecture-note-python-basics-for-ai/blob/main/codes/pytorch/torch_basics.ipynb)


## numpy to tensor

In [1]:
import numpy as np
n_array = np.arange(10).reshape(2,5)
print(n_array)
print("ndim :", n_array.ndim, "shape :", n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim : 2 shape : (2, 5)


In [2]:
import torch
t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim :", t_array.ndim, "shape :", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2 shape : torch.Size([2, 5])


In [3]:
print(t_array.shape)
print(t_array.ndim)
print(t_array.size())


torch.Size([2, 5])
2
torch.Size([2, 5])


### Array to Tensor

##### Data to tensor

In [4]:
data = [[3, 5],[10, 5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

##### ndArray to Tensor

In [5]:
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]])

### numpy like operations

In [6]:
data = [[3, 5, 20],[10, 5, 50], [1, 5, 10]]
x_data = torch.tensor(data)

In [7]:
x_data[1:]

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [8]:
x_data[:2, 1:]

tensor([[ 5, 20],
        [ 5, 50]])

In [9]:
x_data.flatten()

tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [10]:
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [11]:
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]])

In [12]:
x_data.shape

torch.Size([3, 3])

In [13]:
x_data.dtype

torch.int64

In [14]:
x_data.device

device(type='cpu')

In [16]:
if torch.cuda.is_available():
    x_data_cuda = x_data.to('cuda')
x_data_cuda.device

device(type='cuda', index=0)

### Tensor handling

In [17]:
tensor_ex = torch.rand(size=(2, 3, 2))
tensor_ex

tensor([[[0.9376, 0.0449],
         [0.8900, 0.5505],
         [0.5409, 0.7057]],

        [[0.6795, 0.0266],
         [0.4859, 0.7426],
         [0.6445, 0.3764]]])

In [18]:
tensor_ex.view([-1, 6])

tensor([[0.9376, 0.0449, 0.8900, 0.5505, 0.5409, 0.7057],
        [0.6795, 0.0266, 0.4859, 0.7426, 0.6445, 0.3764]])

In [19]:
tensor_ex.reshape([-1,6])

tensor([[0.9376, 0.0449, 0.8900, 0.5505, 0.5409, 0.7057],
        [0.6795, 0.0266, 0.4859, 0.7426, 0.6445, 0.3764]])

In [21]:
a = torch.zeros(3, 2)
b = a.view(2, 3)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [22]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [23]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [25]:
a = torch.zeros(3, 2)
b = a.t().reshape(6)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [26]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [27]:
b

tensor([0., 0., 0., 0., 0., 0.])

In [29]:
tensor_ex = torch.rand(size=(2, 1, 2))
tensor_ex.squeeze()

tensor([[0.9393, 0.4048],
        [0.8825, 0.4085]])

In [30]:
tensor_ex = torch.rand(size=(2, 2))
tensor_ex.unsqueeze(0).shape

torch.Size([1, 2, 2])

In [31]:
tensor_ex.unsqueeze(1).shape

torch.Size([2, 1, 2])

In [32]:
tensor_ex.unsqueeze(2).shape

torch.Size([2, 2, 1])

## tensor operations

In [33]:
n1 = np.arange(10).reshape(2,5)
n2 = np.arange(10).reshape(5,2)
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)

t1 + t1

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]])

In [34]:
t1 - t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [35]:
t1 + 10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [36]:
t1 + t2

RuntimeError: ignored

In [37]:
t1 - t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [38]:
t1 + 10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [39]:
n2 = np.arange(10).reshape(5,2)
t2 = torch.FloatTensor(n2)

t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [40]:
t1.dot(t2)

RuntimeError: ignored

In [41]:
t1.matmul(t2)


tensor([[ 60.,  70.],
        [160., 195.]])

In [43]:
a = torch.rand(10)
b = torch.rand(10)
a.dot(b)

tensor(2.7726)

In [44]:
a

tensor([0.7497, 0.5863, 0.6009, 0.6970, 0.6074, 0.7680, 0.3302, 0.0663, 0.3043,
        0.8059])

In [45]:
a = torch.rand(10)
b = torch.rand(10)
a.mm(b)

RuntimeError: ignored

In [46]:
t1.dot(t2)

RuntimeError: ignored

In [47]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [48]:
a = torch.rand(10)
b = torch.rand(10)
a.dot(b)

tensor(2.3878)

In [49]:
a = torch.rand(10)
b = torch.rand(10)
a.mm(b)

RuntimeError: ignored

In [50]:
a = torch.rand(5,2, 3)
b = torch.rand(5)
a.mm(b)

RuntimeError: ignored

In [51]:
a = torch.rand(5,2, 3)
b = torch.rand(3)
a.matmul(b)

tensor([[0.8846, 0.9696],
        [0.8540, 0.8274],
        [0.9706, 0.2823],
        [0.6618, 0.9058],
        [0.8551, 0.4887]])

In [61]:
a[0].mm(torch.unsqueeze(b,1)).squeeze()



tensor([0.8846, 0.9696])

In [62]:
a[1].mm(torch.unsqueeze(b,1))


tensor([[0.8540],
        [0.8274]])

In [63]:
a[2].mm(torch.unsqueeze(b,1))


tensor([[0.9706],
        [0.2823]])

In [64]:
a[3].mm(torch.unsqueeze(b,1))


tensor([[0.6618],
        [0.9058]])

In [65]:
a[4].mm(torch.unsqueeze(b,1))


tensor([[0.8551],
        [0.4887]])

## tensor operations for ML/DL formula

In [66]:
import torch
import torch.nn.functional as F

tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim=0)
h_tensor


tensor([0.3458, 0.4224, 0.2318])

In [67]:
y = torch.randint(5, (10,5))
y_label = y.argmax(dim=1)

y_label

tensor([3, 1, 2, 2, 2, 2, 0, 1, 3, 0])

In [68]:
torch.nn.functional.one_hot(y_label)

tensor([[0, 0, 0, 1],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0]])

In [69]:
torch.nn.functional.one_hot(y_label)


tensor([[0, 0, 0, 1],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0]])

In [70]:
import itertools
a = [1, 2, 3]
b = [4, 5]
list(itertools.product(a, b))

[(1, 4), (1, 5), (2, 4), (2, 5), (3, 4), (3, 5)]

In [71]:
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b)

tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5],
        [3, 4],
        [3, 5]])

## torch autogard

$$
y = w^2 \\ 
z = 10*y + 25 \\
z = 10*w^2 + 25 
$$

In [74]:
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z = 10*y + 50
z.backward()
w.grad

tensor(40.)

In [75]:
w.grad

tensor(40.)

$$ Q = 3a^3 - b^2  $$

In [76]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

a.grad 

tensor([36., 81.])

In [77]:
b.grad

tensor([-12.,  -8.])

$$ \frac{\partial Q}{\partial a} = 9a^2 $$  

$$ \frac{\partial Q}{\partial b} = -2b $$

In [ ]:
a.grad

In [ ]:
b.grad